### ISSUE TITLE
EntityCard e mapa bugado

### ISSUE THREAD

**Issue by angelonetho** [Ru4nGR/sisdle_web#16]
![image](https://user-images.githubusercontent.com/61638268/125847845-181d7108-1b26-4997-9818-3cb86057fdbd.png)
O Mapa não se adapta ás telas mais largas

**Comment by Imenatrix** [comment]
Em que branch esse comportamento foi observado? Testei em um monitor 1080p e observei a mesma coisa, porem acredito que resolvi isso em #14 pois o problema foi introduzido durante a implementação da animação de abertura da EntityCard.

**Comment by angelonetho** [comment]
O bug é perceptível a partir de #14. Aconteceu na resolução 2560x1080

**Comment by Imenatrix** [comment]
Resolvido em #14. Fechando.
